spring:

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      database: postgresql
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format-sql: true
        enable_lazy_load_no_trans: true
