spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/db_talhao_manager
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456}
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:postgis}

jpa:
  hibernate:
    ddl-auto: update
    database: postgresql
  show-sql: true
  database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

spatial: org.hibernate.spatial.dialect.postgis.PostgisDialect

